# Generated by Django 5.2.17 on 2026-08-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='auto_send_whatsapp',
            field=models.BooleanField(default=False, help_text='Automatically send an invoice/balance message after each sale or payment when Cloud API credentials are configured.'),
        ),
    ]
