import re

from django.conf import settings
from django.utils.translation import activate, get_language


# Business-first Somali wording used consistently across the complete interface.
# Longer phrases are replaced first so a precise phrase wins over a single word.
SOMALI_PHRASES = {
    "Your whole gas business, in one clear view.": "Ganacsigaaga gaaska oo dhan, hal meel oo si cad looga maamulo.",
    "Track every gas cylinder, customer, payment, and daily result without searching through paper books.": "La soco haan kasta, macmiil kasta, lacag-bixin kasta iyo natiijada maalinlaha ah adigoon buugaag waraaqo ah ka dhex raadin.",
    "Only authorized company staff can access this system.": "Nidaamkan waxaa geli kara oo keliya shaqaalaha ay shirkaddu oggolaansho siisay.",
    "A quick view of today’s gas sales, cash, balances, and stock.": "Muuqaal kooban oo ku saabsan iibka gaaska, lacagta, deymaha iyo kaydka maanta.",
    "Search existing customers by phone or create a new customer while recording the sale": "Macmiil hore taleefankiisa ku raadi ama macmiil cusub samee adigoo iibka diiwaangelinaya",
    "Existing customers will be suggested automatically. A new number creates a new customer.": "Macaamiishii hore si toos ah ayaa loo soo jeedinayaa. Lambar cusubna macmiil cusub ayuu samaynayaa.",
    "Start with one line. Add another only when the customer buys more than one product.": "Ku bilow hal saf. Saf kale ku dar keliya marka macmiilku iibsanayo wax ka badan hal badeecad.",
    "Choose a suggestion above, or enter the name for a new customer.": "Ka dooro macmiilka kore ama geli magaca macmiilka cusub.",
    "Select cooking machine, new cylinder, or cylinder gas from the product list.": "Liiska badeecadaha ka dooro shoolad, haan cusub ama gaaska haanta.",
    "No existing customer found. Enter their name below to add them with this sale.": "Macmiil hore lama helin. Hoos ku qor magaciisa si iibkan loogu daro.",
    "Existing customer selected · No unpaid balance": "Macmiil hore ayaa la doortay · Deyn laguma laha",
    "Opening cylinder gas stock": "Kaydka bilowga ee gaaska haanta",
    "Chart is unavailable, but today’s totals above are current.": "Jaantusku hadda ma muuqdo, balse tirooyinka maanta ee kore waa sax.",
    "Choose payment status and save once": "Dooro xaaladda lacag-bixinta, dabadeed hal mar kaydi",
    "Full payment received now": "Lacagta oo dhan hadda waa la helay",
    "Customer will pay later": "Macmiilku mar dambe ayuu bixinayaa",
    "No second payment page is needed.": "Looma baahna bog kale oo lacag-bixin ah.",
    "Search by name or phone number to see purchases and unpaid balances.": "Magac ama taleefan ku raadi si aad u aragto iibsiyada iyo deymaha aan la bixin.",
    "Complete purchase and payment history in one place.": "Taariikhda iibsiga iyo lacag-bixinta oo dhammaystiran hal meel ka eeg.",
    "Every invoice, payment, and remaining balance": "Qaansheegad kasta, lacag-bixin kasta iyo deynta weli harsan",
    "Every amount received for this invoice": "Lacag kasta oo qaansheegaddan laga helay",
    "This invoice currently has its full amount outstanding.": "Lacagta qaansheegaddan oo dhan weli waa deyn.",
    "Manage cooking machines, new cylinders, and the cylinder gas customers buy regularly.": "Maamul shooladaha, haamaha cusub iyo gaaska haamaha ee macaamiishu joogtada u iibsadaan.",
    "Automatic sales and stock received": "Iibka otomaatigga ah iyo kaydka la soo guddoomay",
    "Track the available quantity of this product": "La soco tirada badeecaddan ee kaydka ku jirta",
    "Enter the selling price and what this product costs the company": "Geli qiimaha iibka iyo kharashka ay badeecaddani shirkadda ku joogto",
    "Choose one of the three product types": "Dooro mid ka mid ah saddexda nooc ee badeecadaha",
    "Keep operating costs beside your sales records.": "Kharashaadka hawlgalka ku hay diiwaanka iibka agtiisa.",
    "Review units, revenue, payments, and costs for any period.": "Muddo kasta ka eeg tirada, dakhliga, lacag-bixinta iyo kharashaadka.",
    "Sales less product costs and expenses": "Iibka marka laga jaro kharashka badeecadaha iyo kharashaadka kale",
    "Control who can sign in and keep each transaction connected to the person who recorded it.": "Xakamee cidda geli karta nidaamka, macaamil kastana ku xidh shaqaalihii diiwaangeliyey.",
    "Employees handle customers and sales. Only administrators can change stock, products, expenses, reports, settings, or employee accounts.": "Shaqaaluhu waxay maamulaan macaamiisha iyo iibka. Maamulaha oo keliya ayaa beddeli kara kaydka, badeecadaha, kharashaadka, warbixinnada, dejimaha iyo akoonnada shaqaalaha.",
    "Create a secure sign-in for an authorized staff member.": "U samee gelitaan ammaan ah shaqaale la oggolaaday.",
    "Update the profile, password, or sign-in authorization.": "Cusboonaysii xogta shaqaalaha, erayga sirta ah ama oggolaanshaha gelitaanka.",
    "These details appear on invoices and customer messages.": "Xogtani waxay ka muuqanaysaa qaansheegadaha iyo farriimaha macaamiisha.",
    "Use a strong password that you do not use anywhere else.": "Adeegso eray sir ah oo adag oo aadan meel kale ku isticmaalin.",
    "Save contact details once and use them on every future sale.": "Xogta xiriirka hal mar kaydi, kadibna iib kasta oo dambe ku isticmaal.",
    "Choose cooking machine, new cylinder, or cylinder gas. Each has its own price and stock.": "Dooro shoolad, haan cusub ama gaaska haanta. Mid kastaa wuxuu leeyahay qiime iyo kayd u gaar ah.",
    "Update prices and reorder levels. Use Receive stock to increase quantities.": "Cusboonaysii qiimayaasha iyo heerka dib-u-dalabka. Adeegso ‘Soo guddoon kayd’ si tirada loo kordhiyo.",
    "Choose a product and enter the quantity received.": "Dooro badeecadda oo geli tirada la soo guddoomay.",
    "Customer:": "Macmiil:",
    "Outstanding balance:": "Deynta harsan:",
    "Customer book": "Diiwaanka macaamiisha",
    "Customer record": "Diiwaanka macmiilka",
    "Contact details": "Xogta xiriirka",
    "Purchase history": "Taariikhda iibsiga",
    "Primary phone": "Taleefanka koowaad",
    "Alternate phone": "Taleefan kale",
    "Customer since": "Macmiil tan iyo",
    "Total purchased": "Wadarta uu iibsaday",
    "Balance due": "Deynta lagu leeyahay",
    "Products supplied": "Badeecadaha la bixiyey",
    "Product & size": "Badeecadda & cabbirka",
    "Complete sale": "Dhammaystir iibka",
    "Payment status": "Xaaladda lacag-bixinta",
    "Payment method": "Habka lacag-bixinta",
    "Payment now": "Lacagta hadda",
    "Items subtotal": "Wadarta badeecadaha",
    "Invoice total": "Wadarta qaansheegadda",
    "Save & complete sale": "Kaydi oo dhammaystir iibka",
    "Add another product": "Ku dar badeecad kale",
    "Customer phone number": "Taleefanka macmiilka",
    "Customer & date": "Macmiilka & taariikhda",
    "Customer name": "Magaca macmiilka",
    "Sale date": "Taariikhda iibka",
    "Unit price": "Qiimaha halkii xabbo",
    "Payment history": "Taariikhda lacag-bixinta",
    "Outstanding balance": "Deynta harsan",
    "Record payment": "Diiwaangeli lacag-bixin",
    "Mark paid": "U calaamadee in la bixiyey",
    "Mark fully paid": "U calaamadee in si buuxda loo bixiyey",
    "Record partial payment": "Diiwaangeli lacag-bixin qayb ah",
    "Results update automatically": "Natiijooyinku si toos ah ayay isu cusboonaysiinayaan",
    "Report updates automatically": "Warbixintu si toos ah ayay isu cusboonaysiinaysaa",
    "Update payment": "Cusboonaysii lacag-bixinta",
    "Remaining balance paid in full": "Deyntii hartay si buuxda ayaa loo bixiyey",
    "This invoice is already paid in full.": "Qaansheegaddan hore ayaa si buuxda loo bixiyey.",
    "Paid in full": "Si buuxda ayaa loo bixiyey",
    "Print invoice": "Daabac qaansheegadda",
    "Send WhatsApp": "WhatsApp ku dir",
    "Received by": "Waxaa qabtay",
    "Sale notes": "Faahfaahinta iibka",
    "Bill to": "Ku socota",
    "Invoice details": "Faahfaahinta qaansheegadda",
    "Payment information": "Macluumaadka lacag-bixinta",
    "Amount paid": "Lacagta la bixiyey",
    "PAID IN FULL": "SI BUUXDA AYAA LOO BIXIYEY",
    "Cooking gas cylinder supplies": "Alaabada gaaska iyo haamaha",
    "the company office": "xafiiska shirkadda",
    "Products & stock": "Badeecadaha & kaydka",
    "Product details": "Faahfaahinta badeecadda",
    "Price and cost": "Qiimaha iibka iyo kharashka",
    "Stock controls": "Xakamaynta kaydka",
    "Current stock:": "Kaydka hadda:",
    "Receive stock": "Soo guddoon kayd",
    "Add product": "Ku dar badeecad",
    "Recent stock movements": "Dhaqdhaqaaqyadii kaydka ee u dambeeyey",
    "Quantity change": "Isbeddelka tirada",
    "Opening stock": "Kaydka bilowga",
    "Stock received": "Kayd la soo guddoomay",
    "Product sold": "Badeecad la iibiyey",
    "Sales & invoices": "Iibka & qaansheegadaha",
    "All payment statuses": "Dhammaan xaaladaha lacag-bixinta",
    "Sale total": "Wadarta iibka",
    "Record sale": "Diiwaangeli iib",
    "Record a sale": "Diiwaangeli iib",
    "New sale": "Iib cusub",
    "Today’s sales": "Iibka maanta",
    "Gas supplied": "Gaaska la bixiyey",
    "Cash collected": "Lacagta la qabtay",
    "Customer balance": "Deynta macaamiisha",
    "Today’s gross profit": "Faa’iidada guud ee maanta",
    "Today’s expenses": "Kharashaadka maanta",
    "Net cash today": "Lacagta saafiga ah maanta",
    "Open reports": "Fur warbixinnada",
    "Last 7 days": "7-dii maalmood ee u dambeeyey",
    "Report period": "Muddada warbixinta",
    "Today": "Maanta",
    "This month": "Bishan",
    "Last month": "Bishii hore",
    "Custom range": "Muddo gaar ah",
    "Sales value compared with cash collected": "Qiimaha iibka marka loo barbar dhigo lacagta la qabtay",
    "Stock attention": "Kayd u baahan fiiro",
    "View stock": "Eeg kaydka",
    "Stock levels look good": "Heerarka kaydku waa wanaagsan yihiin",
    "No active product is below its reorder level.": "Ma jiro badeecad shaqaynaysa oo ka hoosaysa heerka dib-u-dalabka.",
    "Recent sales": "Iibyadii u dambeeyey",
    "Latest invoices and payment status": "Qaansheegadihii u dambeeyey iyo xaaladda lacag-bixinta",
    "Recorded by": "Waxaa diiwaangeliyey",
    "Full report": "Warbixin buuxda",
    "Refill units sold today": "Tirada gaaska maanta la iibiyey",
    "Payments received today": "Lacag-bixinnada maanta la helay",
    "Still unpaid across invoices": "Deynta weli ku harsan qaansheegadaha",
    "Expenses": "Kharashaadka",
    "Record expense": "Diiwaangeli kharash",
    "All recorded expenses": "Dhammaan kharashaadka la diiwaangeliyey",
    "Lifetime total": "Wadarta guud ilaa hadda",
    "Sales report": "Warbixinta iibka",
    "Business performance": "Waxqabadka ganacsiga",
    "Print report": "Daabac warbixinta",
    "Sales value": "Qiimaha iibka",
    "Cylinder gas sold": "Gaaska haamaha ee la iibiyey",
    "Operating profit": "Faa’iidada hawlgalka",
    "Daily sales": "Iibka maalinlaha ah",
    "Gross profit": "Faa’iidada guud",
    "Best-selling cylinders": "Haamaha ugu iibka badan",
    "Ranked by quantity": "Loo kala hormariyey tirada",
    "Employees": "Shaqaalaha",
    "Administrator": "Maamule",
    "Administration": "Maamulka",
    "Add employee": "Ku dar shaqaale",
    "Employee": "Shaqaale",
    "Contact": "Xiriir",
    "Account": "Akoon",
    "Activity": "Hawlaha",
    "Last sign-in": "Gelitaankii u dambeeyey",
    "Authorized": "La oggolaaday",
    "Deactivated": "La joojiyey",
    "Manage": "Maamul",
    "View all": "Eeg dhammaan",
    "Simple, safe access": "Gelitaan fudud oo ammaan ah",
    "Management": "Maamulka",
    "Dashboard": "Bogga guud",
    "Workspace": "Goobta shaqada",
    "Business manager": "Maamulka ganacsiga",
    "Finance": "Maaliyadda",
    "Reports": "Warbixinnada",
    "Change password": "Beddel erayga sirta ah",
    "Company settings": "Dejimaha shirkadda",
    "Sign out": "Ka bax",
    "Home": "Hoyga",
    "Stock": "Kaydka",
    "Sales": "Iibka",
    "Customers": "Macaamiisha",
    "Add customer": "Ku dar macmiil",
    "View record": "Eeg diiwaanka",
    "Edit customer": "Wax ka beddel macmiilka",
    "Edit product": "Wax ka beddel badeecadda",
    "Edit employee": "Wax ka beddel shaqaalaha",
    "Edit": "Wax ka beddel",
    "Search": "Raadi",
    "Filter": "Kala saar",
    "Apply": "Dhaqan geli",
    "From": "Laga bilaabo",
    "To": "Ilaa",
    "Date": "Taariikh",
    "Product": "Badeecad",
    "Type": "Nooc",
    "Quantity": "Tiro",
    "Units": "Xabbo",
    "Movement": "Dhaqdhaqaaq",
    "Reference": "Tixraac",
    "Description": "Faahfaahin",
    "Category": "Qaybta",
    "Amount": "Lacag",
    "Invoice": "Qaansheegad",
    "INVOICE": "QAANSHEEGAD",
    "Customer": "Macmiil",
    "Status": "Xaalad",
    "Subtotal": "Wadar-hoosaad",
    "Discount": "Qiimo-dhimis",
    "Total": "Wadar",
    "Balance": "Deyn",
    "Paid": "La bixiyey",
    "Unpaid": "Aan la bixin",
    "Partially paid": "Qayb ahaan la bixiyey",
    "Cash": "Lacag caddaan ah",
    "Mobile money": "Lacagta moobilka",
    "Bank transfer": "Wareejin bangi",
    "Other": "Kale",
    "New cylinder": "Haan gaas cusub",
    "Cylinder gas": "Gaaska haanta",
    "Cooking machine": "Shoolad",
    "Active": "Shaqaynaya",
    "Inactive": "Aan shaqaynayn",
    "Selling price": "Qiimaha iibka",
    "Cost price": "Qiimaha kharashka",
    "Reorder level": "Heerka dib-u-dalabka",
    "Size / model": "Cabbirka / nooca",
    "Product type": "Nooca badeecadda",
    "Name": "Magac",
    "Phone": "Taleefan",
    "Phone number": "Lambarka taleefanka",
    "Address": "Cinwaan",
    "Notes": "Qoraallo",
    "Username": "Magaca gelitaanka",
    "First name": "Magaca hore",
    "Last name": "Magaca dambe",
    "Email": "Iimayl",
    "Job title": "Jagada shaqada",
    "Authorized to sign in": "Loo oggolaaday inuu galo",
    "Password": "Erayga sirta ah",
    "Confirm password": "Xaqiiji erayga sirta ah",
    "Welcome back": "Soo dhawoow mar kale",
    "Sign in to open today’s workspace.": "Gal si aad u furto goobta shaqada ee maanta.",
    "Sign in": "Gal",
    "Secure business workspace": "Goob ganacsi oo ammaan ah",
    "Every transaction recorded": "Macaamil kasta waa la diiwaangeliyey",
    "Know what is available": "Ogow waxa kaydka ku jira",
    "Balances by phone number": "Deymaha oo taleefan lagu raadin karo",
    "Every transaction recorded": "Macaamil kasta waa la diiwaangeliyey",
    "Cancel": "Ka noqo",
    "Save": "Kaydi",
    "Back": "Dib u noqo",
    "Previous": "Hore",
    "Next": "Xiga",
    "Never": "Weligii",
    "Nothing here yet": "Weli waxba kuma jiraan",
    "New records will appear here as soon as they are added.": "Diiwaannada cusub halkan ayay ka muuqanayaan marka lagu daro.",
    "Here is what is happening across the business today.": "Waa kan xaaladda guud ee ganacsiga maanta.",
    "Value invoiced today": "Qiimaha maanta qaansheegadaha lagu qoray",
    "Cylinders and cookers today": "Haamaha iyo shooladaha maanta",
    "All payments received": "Dhammaan lacag-bixinnada la helay",
    "Across open invoices": "Dhammaan qaansheegadaha aan xirmin",
    "No sales recorded yet": "Weli iib lama diiwaangelin",
    "Record the first sale and it will appear here.": "Diiwaangeli iibka ugu horreeya, halkan ayuu ka muuqan doonaa.",
    "Find any invoice by number, customer name, or phone.": "Qaansheegad kasta ku raadi lambarkeeda, magaca macmiilka ama taleefankiisa.",
    "Invoice, customer, or phone number…": "Qaansheegad, macmiil ama taleefan…",
    "No sales found": "Wax iib ah lama helin",
    "Adjust the filter or record a new sale.": "Beddel kala-soocidda ama diiwaangeli iib cusub.",
    "Search name, phone number, or alternate phone…": "Ku raadi magac, taleefan ama taleefanka kale…",
    "No customers found": "Macaamiil lama helin",
    "Try a different phone number or create a new customer record.": "Isku day taleefan kale ama samee diiwaan macmiil cusub.",
    "No purchases yet": "Weli wax iibsi ah ma jiro",
    "This customer’s invoices will appear here.": "Qaansheegadaha macmiilkan halkan ayay ka muuqan doonaan.",
    "Search products by name or size…": "Badeecadaha ku raadi magac ama cabbir…",
    "No products found": "Badeecado lama helin",
    "Add cooking machine, new cylinder, or cylinder gas.": "Ku dar shoolad, haan cusub ama gaaska haanta.",
    "Ask an administrator to add the first product.": "Ka codso maamulaha inuu ku daro badeecadda ugu horreysa.",
    "No stock movements yet": "Weli dhaqdhaqaaq kayd ma jiro",
    "Opening stock and future transactions will appear here.": "Kaydka bilowga iyo macaamillada dambe halkan ayay ka muuqan doonaan.",
    "No expenses recorded": "Wax kharash ah lama diiwaangelin",
    "Add transport, utilities, supplies, and other operating expenses.": "Ku dar gaadiidka, adeegyada, sahayda iyo kharashaadka kale ee hawlgalka.",
    "No sales in this period": "Muddadan wax iib ah ma jiro",
    "Choose another date range or begin recording sales.": "Dooro muddo kale ama bilow diiwaangelinta iibka.",
    "No ranking yet": "Weli kala-hormarin ma jirto",
    "Best-selling cylinder sizes will appear here.": "Cabbirrada haamaha ugu iibka badan halkan ayay ka muuqan doonaan.",
    "No employees yet": "Weli shaqaale lama darin",
    "Add the first employee and authorize their sign-in.": "Ku dar shaqaalaha ugu horreeya oo u oggolow gelitaanka nidaamka.",
    "Search existing customers": "Raadi macaamiishii hore",
    "Existing customer selected": "Macmiil hore ayaa la doortay",
    "No unpaid balance": "Deyn aan la bixin ma jirto",
    "No balance": "Deyn ma leh",
    "New transaction": "Macaamil cusub",
    "Transactions": "Macaamillada",
    "Inventory": "Kaydka",
    "Cash out": "Lacag-bax",
    "Recorded": "La diiwaangeliyey",
    "Left": "Harsan",
    "Out": "Ka dhammaaday",
    "Qty": "Tiro",
    "Joined": "Ku soo biiray",
    "Method": "Habka",
    "Total amount": "Wadarta lacagta",
    "Search name, phone number, or alternate phone": "Ku raadi magac, taleefan ama taleefanka kale",
    "Start typing the phone number…": "Bilow qorista lambarka taleefanka…",
    "Enter or confirm the customer name": "Geli ama xaqiiji magaca macmiilka",
    "Delivery or warranty notes (optional)": "Qoraal gaarsiin ama dammaanad ah (ikhtiyaari)",
    "Open more navigation": "Fur liiska kale",
    "Use the customer's WhatsApp number, including country code when possible.": "Adeegso lambarka WhatsApp-ka macmiilka, kuna dar summadda dalka haddii ay suurtagal tahay.",
    "Cylinder size or cooking-machine model, for example 13 kg or 2 burner": "Cabbirka haanta ama nooca shooladda, tusaale 13 kg ama laba dab-shide.",
    "Used by the employee to sign in.": "Shaqaaluhu wuxuu magacan ugu gelayaa nidaamka.",
    "Leave blank to keep the current password.": "Bannaan uga tag si erayga sirta ah ee hadda jira loo sii hayo.",
    "Add customer": "Ku dar macmiil",
    "Save customer": "Kaydi macmiilka",
    "Update customer": "Cusboonaysii macmiilka",
    "Save product": "Kaydi badeecadda",
    "Update product": "Cusboonaysii badeecadda",
    "Save payment": "Kaydi lacag-bixinta",
    "Save expense": "Kaydi kharashka",
    "Save settings": "Kaydi dejimaha",
    "Create employee": "Samee shaqaale",
    "Save employee": "Kaydi shaqaalaha",
    "Update password": "Cusboonaysii erayga sirta ah",
    "Add quantities": "Ku dar tirooyin",
    "Transport": "Gaadiid",
    "Utilities": "Adeegyada muhiimka ah",
    "Salary / wages": "Mushahar / gunno shaqo",
    "Maintenance": "Dayactir",
    "Supplies": "Sahay",
    "Cash collected today": "Lacagta maanta la qabtay",
    "Collected": "La qabtay",
    "Sales employee": "Shaqaale iib",
    " sales ": " iib ",
    " payments": " lacag-bixinno",
    "units supplied": "xabbo ayaa la bixiyey",
    "Amount charged for gas when the customer already has a cylinder.": "Lacagta gaaska laga qaado marka macmiilku haan hore u haysto.",
    "Company cost of the gas supplied for one cylinder.": "Kharashka shirkadda ku baxa gaaska hal haan lagu buuxiyo.",
    "Company name": "Magaca shirkadda",
    "Invoice footer": "Qoraalka hoose ee qaansheegadda",
    "Automatically send an invoice/balance message after each sale or payment when Cloud API credentials are configured.": "Si otomaatig ah u dir farriinta qaansheegadda ama deynta iib ama lacag-bixin kasta ka dib marka adeegga WhatsApp la diyaariyo.",
    "Auto send whatsapp": "Si otomaatig ah WhatsApp ugu dir",
    "Currency": "Lacagta la adeegsado",
    "Old password": "Erayga sirta ah ee hore",
    "New password": "Erayga sirta ah ee cusub",
    "New password confirmation": "Xaqiiji erayga sirta ah ee cusub",
    "Your password can’t be too similar to your other personal information.": "Erayga sirta ahi yuusan aad ugu ekaan xogtaada gaarka ah.",
    "Your password must contain at least 8 characters.": "Erayga sirta ahi waa inuu ka kooban yahay ugu yaraan 8 xaraf.",
    "Your password can’t be a commonly used password.": "Erayga sirta ahi yuusan noqon mid si badan loo isticmaalo.",
    "Your password can’t be entirely numeric.": "Erayga sirta ahi yuusan tirooyin keliya noqon.",
    "The two password fields didn’t match.": "Labada eray sir ah isma waafaqin.",
    "Enter a valid email address.": "Geli cinwaan iimayl oo sax ah.",
    "Enter a valid customer phone number.": "Geli taleefan macmiil oo sax ah.",
    "Administrator access is required.": "Gelitaanka maamulaha ayaa loo baahan yahay.",
    "This account has not been authorized by an administrator.": "Akoonkan weli maamuluhu uma oggolaan gelitaanka.",
    "Product added to inventory.": "Badeecadda waxaa lagu daray kaydka.",
    "Product updated.": "Badeecadda waa la cusboonaysiiyey.",
    "Stock received and recorded.": "Kaydka waa la soo guddoomay waana la diiwaangeliyey.",
    "Payment recorded and balance updated.": "Lacag-bixinta waa la diiwaangeliyey, deyntana waa la cusboonaysiiyey.",
    "Expense recorded.": "Kharashka waa la diiwaangeliyey.",
    "Company settings updated.": "Dejimaha shirkadda waa la cusboonaysiiyey.",
    "Customer details updated.": "Xogta macmiilka waa la cusboonaysiiyey.",
    "Monday": "Isniin",
    "Tuesday": "Talaado",
    "Wednesday": "Arbaco",
    "Thursday": "Khamiis",
    "Friday": "Jimco",
    "Saturday": "Sabti",
    "Sunday": "Axad",
    "January": "Jannaayo",
    "February": "Febraayo",
    "March": "Maarso",
    "April": "Abriil",
    "May": "Maajo",
    "June": "Juun",
    "July": "Luulyo",
    "August": "Agoosto",
    "September": "Sebteembar",
    "October": "Oktoobar",
    "November": "Nofeembar",
    "December": "Diseembar",
    "Mon": "Isn",
    "Tue": "Tal",
    "Wed": "Arb",
    "Thu": "Kha",
    "Fri": "Jim",
    "Sat": "Sab",
    "Sun": "Axa",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Abr",
    "Jun": "Juun",
    "Jul": "Luu",
    "Aug": "Ago",
    "Sep": "Seb",
    "Oct": "Okt",
    "Nov": "Nof",
    "Dec": "Dis",
    "This field is required.": "Goobtan waa qasab.",
    "Enter a valid value.": "Geli xog sax ah.",
}


SOMALI_PATTERNS = [
    (re.compile(r"(GS-[A-Z0-9-]+) was marked paid\. The remaining balance was recorded\."), r"\1 waxaa loo calaamadeeyey in la bixiyey. Deyntii hartayna waa la diiwaangeliyey."),
    (re.compile(r"Good day, "), "Maalin wanaagsan, "),
    (re.compile(r"(\d+) invoices recorded"), r"\1 qaansheegadood ayaa la diiwaangeliyey"),
    (re.compile(r"(\d+) products at or below reorder level"), r"\1 badeecadood ayaa gaaray ama ka hooseeya heerka dib-u-dalabka"),
    (re.compile(r"(\d+) product at or below reorder level"), r"\1 badeecad ayaa gaartay ama ka hooseysa heerka dib-u-dalabka"),
    (re.compile(r"(\d+) in stock"), r"\1 ayaa kaydka ku jira"),
    (re.compile(r"(\d+) available"), r"\1 ayaa diyaar ah"),
    (re.compile(r"(\d+) sold"), r"\1 ayaa la iibiyey"),
    (re.compile(r"(\d+) sales"), r"\1 iib"),
    (re.compile(r"(\d+) payments"), r"\1 lacag-bixin"),
    (re.compile(r"Showing (.*?) to (.*?)<"), r"Waxaa la muujinayaa \1 ilaa \2<"),
    (re.compile(r"Recorded (.*?) by "), r"Waxaa la diiwaangeliyey \1, waxaana diiwaangeliyey "),
    (re.compile(r"Balance due: "), "Deynta harsan: "),
    (re.compile(r"reorder at (\d+)"), r"dib u dalbo marka uu gaaro \1"),
]


class SomaliTranslationMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response
        self.ordered_phrases = sorted(SOMALI_PHRASES.items(), key=lambda item: len(item[0]), reverse=True)

    def __call__(self, request):
        previous_language = get_language()
        selected_language = request.COOKIES.get(settings.LANGUAGE_COOKIE_NAME, previous_language or "en")
        if selected_language not in {"en", "so"}:
            selected_language = "en"
        activate(selected_language)
        request.LANGUAGE_CODE = selected_language
        try:
            response = self.get_response(request)
            content_type = response.get("Content-Type", "")
            if selected_language != "so" or response.streaming or "text/html" not in content_type:
                return response
            charset = response.charset or "utf-8"
            content = response.content.decode(charset)
            for english, somali in self.ordered_phrases:
                content = content.replace(english, somali)
            for pattern, replacement in SOMALI_PATTERNS:
                content = pattern.sub(replacement, content)
            response.content = content.encode(charset)
            return response
        finally:
            activate(previous_language or settings.LANGUAGE_CODE)
